name: Issue Response Handler

on:
  issues:
    types: [opened]

permissions:
  contents: read  

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
    
    - name: Print Username
      run: |
        echo "Hello ${{ github.event.issue.user.login }}"